<a href="https://colab.research.google.com/github/2410030121/DataScience/blob/main/Missing_Values(Student_data).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv("students_data.csv", parse_dates=['enrolled_date'])
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,jane smith,16.0,female,11,75.0,NaN,66,2022-10-06,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,2022-10-06,GOOD
2,102,Chris P.,NaN,MALE,10,NaN,missing,69,2022-06-12,needs improvement
3,103,jane smith,16.0,FEMALE,10,NaN,missing,62,2022-10-06,average
4,104,Sara O'Neil,16.0,male,11,NaN,96,64,2022-10-06,GOOD
5,105,Mike O’Reilly,16.0,Female,10,NaN,NaN,83,2022-06-12,needs improvement
6,106,ali Khan,17.0,female,11,64.0,NaN,75,2022-06-12,Good
7,107,Sara O'Neil,17.0,female,12,NaN,63,62,2022-11-06,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,2022-06-12,poor
9,109,Robert Brown,17.0,female,12,NaN,missing,97,2022-10-06,needs improvement
10,110,lucy gray,17.0,male,11th,65.0,67,100,2022-06-12,excellent
11,111,Simran Singh,16.0,FEMALE,11th,NaN,missing,95,2022-10-06,average
12,112,Patel R.,17.0,female,11,NaN,87,89,2022-10-06,poor
13,113,Patel R.,17.0,male,10,NaN,NaN,98,2022-06-12,Average
14,114,Ali Khan,17.0,male,12,NaN,91,67,2022-11-06,poor
15,115,Lucy gray,16.0,Female,12,65.0,91,94,2022-06-12,Average
16,116,Chris P.,NaN,Female,11,NaN,NaN,72,2022-11-06,excellent
17,117,Ali Khan,18.0,male,11th,67.0,74,81,2022-10-06,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022-11-06,average
19,119,Patel R.,17.0,MALE,11th,73.0,NaN,90,2022-06-12,Good
20,120,Sara O'Neil,17.0,Male,10,NaN,missing,89,2022-10-06,average
21,121,John Doe,18.0,female,11,66.0,72,94,2022-10-06,Average
22,122,Sara O'Neil,17.0,MALE,11th,75.0,NaN,66,2022-10-06,good student
23,123,jane smith,17.0,Female,11th,NaN,missing,63,2022-06-12,excellent
24,124,John Doe,18.0,MALE,11th,NaN,NaN,91,2022-06-12,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,2022-10-06,Average
26,126,John Doe,NaN,Male,10th,64.0,missing,67,2022-06-12,good student
27,127,Simran Singh,16.0,FEMALE,12,NaN,76,80,2022-06-12,poor
28,128,Sara O'Neil,17.0,female,11,NaN,64,89,2022-10-06,average
29,129,Patel R.,17.0,male,11,NaN,64,83,2022-11-06,Average
30,129,Patel R.,17.0,male,11,NaN,64,83,2022-11-06,Average

In [ ]:
new_df=df.fillna(0)
new_df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,jane smith,16.0,female,11,75.0,0,66,2022-10-06,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,2022-10-06,GOOD
2,102,Chris P.,0.0,MALE,10,0.0,missing,69,2022-06-12,needs improvement
3,103,jane smith,16.0,FEMALE,10,0.0,missing,62,2022-10-06,average
4,104,Sara O'Neil,16.0,male,11,0.0,96,64,2022-10-06,GOOD
5,105,Mike O’Reilly,16.0,Female,10,0.0,0,83,2022-06-12,needs improvement
6,106,ali Khan,17.0,female,11,64.0,0,75,2022-06-12,Good
7,107,Sara O'Neil,17.0,female,12,0.0,63,62,2022-11-06,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,2022-06-12,poor
9,109,Robert Brown,17.0,female,12,0.0,missing,97,2022-10-06,needs improvement
10,110,lucy gray,17.0,male,11th,65.0,67,100,2022-06-12,excellent
11,111,Simran Singh,16.0,FEMALE,11th,0.0,missing,95,2022-10-06,average
12,112,Patel R.,17.0,female,11,0.0,87,89,2022-10-06,poor
13,113,Patel R.,17.0,male,10,0.0,0,98,2022-06-12,Average
14,114,Ali Khan,17.0,male,12,0.0,91,67,2022-11-06,poor
15,115,Lucy gray,16.0,Female,12,65.0,91,94,2022-06-12,Average
16,116,Chris P.,0.0,Female,11,0.0,0,72,2022-11-06,excellent
17,117,Ali Khan,18.0,male,11th,67.0,74,81,2022-10-06,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022-11-06,average
19,119,Patel R.,17.0,MALE,11th,73.0,0,90,2022-06-12,Good
20,120,Sara O'Neil,17.0,Male,10,0.0,missing,89,2022-10-06,average
21,121,John Doe,18.0,female,11,66.0,72,94,2022-10-06,Average
22,122,Sara O'Neil,17.0,MALE,11th,75.0,0,66,2022-10-06,good student
23,123,jane smith,17.0,Female,11th,0.0,missing,63,2022-06-12,excellent
24,124,John Doe,18.0,MALE,11th,0.0,0,91,2022-06-12,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,2022-10-06,Average
26,126,John Doe,0.0,Male,10th,64.0,missing,67,2022-06-12,good student
27,127,Simran Singh,16.0,FEMALE,12,0.0,76,80,2022-06-12,poor
28,128,Sara O'Neil,17.0,female,11,0.0,64,89,2022-10-06,average
29,129,Patel R.,17.0,male,11,0.0,64,83,2022-11-06,Average
30,129,Patel R.,17.0,male,11,0.0,64,83,2022-11-06,Average

In [ ]:
new_df=df.fillna({
    'age':'no age',
    'math_score':0,
    'english_score':0
})
new_df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,jane smith,16.0,female,11,75.0,0,66,2022-10-06,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,2022-10-06,GOOD
2,102,Chris P.,no age,MALE,10,0.0,missing,69,2022-06-12,needs improvement
3,103,jane smith,16.0,FEMALE,10,0.0,missing,62,2022-10-06,average
4,104,Sara O'Neil,16.0,male,11,0.0,96,64,2022-10-06,GOOD
5,105,Mike O’Reilly,16.0,Female,10,0.0,0,83,2022-06-12,needs improvement
6,106,ali Khan,17.0,female,11,64.0,0,75,2022-06-12,Good
7,107,Sara O'Neil,17.0,female,12,0.0,63,62,2022-11-06,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,2022-06-12,poor
9,109,Robert Brown,17.0,female,12,0.0,missing,97,2022-10-06,needs improvement
10,110,lucy gray,17.0,male,11th,65.0,67,100,2022-06-12,excellent
11,111,Simran Singh,16.0,FEMALE,11th,0.0,missing,95,2022-10-06,average
12,112,Patel R.,17.0,female,11,0.0,87,89,2022-10-06,poor
13,113,Patel R.,17.0,male,10,0.0,0,98,2022-06-12,Average
14,114,Ali Khan,17.0,male,12,0.0,91,67,2022-11-06,poor
15,115,Lucy gray,16.0,Female,12,65.0,91,94,2022-06-12,Average
16,116,Chris P.,no age,Female,11,0.0,0,72,2022-11-06,excellent
17,117,Ali Khan,18.0,male,11th,67.0,74,81,2022-10-06,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022-11-06,average
19,119,Patel R.,17.0,MALE,11th,73.0,0,90,2022-06-12,Good
20,120,Sara O'Neil,17.0,Male,10,0.0,missing,89,2022-10-06,average
21,121,John Doe,18.0,female,11,66.0,72,94,2022-10-06,Average
22,122,Sara O'Neil,17.0,MALE,11th,75.0,0,66,2022-10-06,good student
23,123,jane smith,17.0,Female,11th,0.0,missing,63,2022-06-12,excellent
24,124,John Doe,18.0,MALE,11th,0.0,0,91,2022-06-12,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,2022-10-06,Average
26,126,John Doe,no age,Male,10th,64.0,missing,67,2022-06-12,good student
27,127,Simran Singh,16.0,FEMALE,12,0.0,76,80,2022-06-12,poor
28,128,Sara O'Neil,17.0,female,11,0.0,64,89,2022-10-06,average
29,129,Patel R.,17.0,male,11,0.0,64,83,2022-11-06,Average
30,129,Patel R.,17.0,male,11,0.0,64,83,2022-11-06,Average

In [ ]:
new_df=df.ffill()
new_df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,jane smith,16.0,female,11,75.0,NaN,66,2022-10-06,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,2022-10-06,GOOD
2,102,Chris P.,16.0,MALE,10,74.0,missing,69,2022-06-12,needs improvement
3,103,jane smith,16.0,FEMALE,10,74.0,missing,62,2022-10-06,average
4,104,Sara O'Neil,16.0,male,11,74.0,96,64,2022-10-06,GOOD
5,105,Mike O’Reilly,16.0,Female,10,74.0,96,83,2022-06-12,needs improvement
6,106,ali Khan,17.0,female,11,64.0,96,75,2022-06-12,Good
7,107,Sara O'Neil,17.0,female,12,64.0,63,62,2022-11-06,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,2022-06-12,poor
9,109,Robert Brown,17.0,female,12,80.0,missing,97,2022-10-06,needs improvement
10,110,lucy gray,17.0,male,11th,65.0,67,100,2022-06-12,excellent
11,111,Simran Singh,16.0,FEMALE,11th,65.0,missing,95,2022-10-06,average
12,112,Patel R.,17.0,female,11,65.0,87,89,2022-10-06,poor
13,113,Patel R.,17.0,male,10,65.0,87,98,2022-06-12,Average
14,114,Ali Khan,17.0,male,12,65.0,91,67,2022-11-06,poor
15,115,Lucy gray,16.0,Female,12,65.0,91,94,2022-06-12,Average
16,116,Chris P.,16.0,Female,11,65.0,91,72,2022-11-06,excellent
17,117,Ali Khan,18.0,male,11th,67.0,74,81,2022-10-06,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022-11-06,average
19,119,Patel R.,17.0,MALE,11th,73.0,74,90,2022-06-12,Good
20,120,Sara O'Neil,17.0,Male,10,73.0,missing,89,2022-10-06,average
21,121,John Doe,18.0,female,11,66.0,72,94,2022-10-06,Average
22,122,Sara O'Neil,17.0,MALE,11th,75.0,72,66,2022-10-06,good student
23,123,jane smith,17.0,Female,11th,75.0,missing,63,2022-06-12,excellent
24,124,John Doe,18.0,MALE,11th,75.0,missing,91,2022-06-12,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,2022-10-06,Average
26,126,John Doe,17.0,Male,10th,64.0,missing,67,2022-06-12,good student
27,127,Simran Singh,16.0,FEMALE,12,64.0,76,80,2022-06-12,poor
28,128,Sara O'Neil,17.0,female,11,64.0,64,89,2022-10-06,average
29,129,Patel R.,17.0,male,11,64.0,64,83,2022-11-06,Average
30,129,Patel R.,17.0,male,11,64.0,64,83,2022-11-06,Average

In [ ]:
new_df=df.bfill()
new_df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,jane smith,16.0,female,11,75.0,95,66,2022-10-06,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,2022-10-06,GOOD
2,102,Chris P.,16.0,MALE,10,64.0,missing,69,2022-06-12,needs improvement
3,103,jane smith,16.0,FEMALE,10,64.0,missing,62,2022-10-06,average
4,104,Sara O'Neil,16.0,male,11,64.0,96,64,2022-10-06,GOOD
5,105,Mike O’Reilly,16.0,Female,10,64.0,63,83,2022-06-12,needs improvement
6,106,ali Khan,17.0,female,11,64.0,63,75,2022-06-12,Good
7,107,Sara O'Neil,17.0,female,12,80.0,63,62,2022-11-06,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,2022-06-12,poor
9,109,Robert Brown,17.0,female,12,65.0,missing,97,2022-10-06,needs improvement
10,110,lucy gray,17.0,male,11th,65.0,67,100,2022-06-12,excellent
11,111,Simran Singh,16.0,FEMALE,11th,65.0,missing,95,2022-10-06,average
12,112,Patel R.,17.0,female,11,65.0,87,89,2022-10-06,poor
13,113,Patel R.,17.0,male,10,65.0,91,98,2022-06-12,Average
14,114,Ali Khan,17.0,male,12,65.0,91,67,2022-11-06,poor
15,115,Lucy gray,16.0,Female,12,65.0,91,94,2022-06-12,Average
16,116,Chris P.,18.0,Female,11,67.0,74,72,2022-11-06,excellent
17,117,Ali Khan,18.0,male,11th,67.0,74,81,2022-10-06,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022-11-06,average
19,119,Patel R.,17.0,MALE,11th,73.0,missing,90,2022-06-12,Good
20,120,Sara O'Neil,17.0,Male,10,66.0,missing,89,2022-10-06,average
21,121,John Doe,18.0,female,11,66.0,72,94,2022-10-06,Average
22,122,Sara O'Neil,17.0,MALE,11th,75.0,missing,66,2022-10-06,good student
23,123,jane smith,17.0,Female,11th,94.0,missing,63,2022-06-12,excellent
24,124,John Doe,18.0,MALE,11th,94.0,80,91,2022-06-12,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,2022-10-06,Average
26,126,John Doe,16.0,Male,10th,64.0,missing,67,2022-06-12,good student
27,127,Simran Singh,16.0,FEMALE,12,NaN,76,80,2022-06-12,poor
28,128,Sara O'Neil,17.0,female,11,NaN,64,89,2022-10-06,average
29,129,Patel R.,17.0,male,11,NaN,64,83,2022-11-06,Average
30,129,Patel R.,17.0,male,11,NaN,64,83,2022-11-06,Average

In [ ]:
df = df.interpolate()
new_df

/tmp/ipykernel_519/2524736170.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df = df.interpolate()

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,jane smith,16.0,female,11,75.0,95,66,2022-10-06,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,2022-10-06,GOOD
2,102,Chris P.,16.0,MALE,10,64.0,missing,69,2022-06-12,needs improvement
3,103,jane smith,16.0,FEMALE,10,64.0,missing,62,2022-10-06,average
4,104,Sara O'Neil,16.0,male,11,64.0,96,64,2022-10-06,GOOD
5,105,Mike O’Reilly,16.0,Female,10,64.0,63,83,2022-06-12,needs improvement
6,106,ali Khan,17.0,female,11,64.0,63,75,2022-06-12,Good
7,107,Sara O'Neil,17.0,female,12,80.0,63,62,2022-11-06,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,2022-06-12,poor
9,109,Robert Brown,17.0,female,12,65.0,missing,97,2022-10-06,needs improvement
10,110,lucy gray,17.0,male,11th,65.0,67,100,2022-06-12,excellent
11,111,Simran Singh,16.0,FEMALE,11th,65.0,missing,95,2022-10-06,average
12,112,Patel R.,17.0,female,11,65.0,87,89,2022-10-06,poor
13,113,Patel R.,17.0,male,10,65.0,91,98,2022-06-12,Average
14,114,Ali Khan,17.0,male,12,65.0,91,67,2022-11-06,poor
15,115,Lucy gray,16.0,Female,12,65.0,91,94,2022-06-12,Average
16,116,Chris P.,18.0,Female,11,67.0,74,72,2022-11-06,excellent
17,117,Ali Khan,18.0,male,11th,67.0,74,81,2022-10-06,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022-11-06,average
19,119,Patel R.,17.0,MALE,11th,73.0,missing,90,2022-06-12,Good
20,120,Sara O'Neil,17.0,Male,10,66.0,missing,89,2022-10-06,average
21,121,John Doe,18.0,female,11,66.0,72,94,2022-10-06,Average
22,122,Sara O'Neil,17.0,MALE,11th,75.0,missing,66,2022-10-06,good student
23,123,jane smith,17.0,Female,11th,94.0,missing,63,2022-06-12,excellent
24,124,John Doe,18.0,MALE,11th,94.0,80,91,2022-06-12,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,2022-10-06,Average
26,126,John Doe,16.0,Male,10th,64.0,missing,67,2022-06-12,good student
27,127,Simran Singh,16.0,FEMALE,12,NaN,76,80,2022-06-12,poor
28,128,Sara O'Neil,17.0,female,11,NaN,64,89,2022-10-06,average
29,129,Patel R.,17.0,male,11,NaN,64,83,2022-11-06,Average
30,129,Patel R.,17.0,male,11,NaN,64,83,2022-11-06,Average

In [ ]:
df = df.dropna()
new_df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,jane smith,16.0,female,11,75.0,95,66,2022-10-06,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,2022-10-06,GOOD
2,102,Chris P.,16.0,MALE,10,64.0,missing,69,2022-06-12,needs improvement
3,103,jane smith,16.0,FEMALE,10,64.0,missing,62,2022-10-06,average
4,104,Sara O'Neil,16.0,male,11,64.0,96,64,2022-10-06,GOOD
5,105,Mike O’Reilly,16.0,Female,10,64.0,63,83,2022-06-12,needs improvement
6,106,ali Khan,17.0,female,11,64.0,63,75,2022-06-12,Good
7,107,Sara O'Neil,17.0,female,12,80.0,63,62,2022-11-06,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,2022-06-12,poor
9,109,Robert Brown,17.0,female,12,65.0,missing,97,2022-10-06,needs improvement
10,110,lucy gray,17.0,male,11th,65.0,67,100,2022-06-12,excellent
11,111,Simran Singh,16.0,FEMALE,11th,65.0,missing,95,2022-10-06,average
12,112,Patel R.,17.0,female,11,65.0,87,89,2022-10-06,poor
13,113,Patel R.,17.0,male,10,65.0,91,98,2022-06-12,Average
14,114,Ali Khan,17.0,male,12,65.0,91,67,2022-11-06,poor
15,115,Lucy gray,16.0,Female,12,65.0,91,94,2022-06-12,Average
16,116,Chris P.,18.0,Female,11,67.0,74,72,2022-11-06,excellent
17,117,Ali Khan,18.0,male,11th,67.0,74,81,2022-10-06,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022-11-06,average
19,119,Patel R.,17.0,MALE,11th,73.0,missing,90,2022-06-12,Good
20,120,Sara O'Neil,17.0,Male,10,66.0,missing,89,2022-10-06,average
21,121,John Doe,18.0,female,11,66.0,72,94,2022-10-06,Average
22,122,Sara O'Neil,17.0,MALE,11th,75.0,missing,66,2022-10-06,good student
23,123,jane smith,17.0,Female,11th,94.0,missing,63,2022-06-12,excellent
24,124,John Doe,18.0,MALE,11th,94.0,80,91,2022-06-12,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,2022-10-06,Average
26,126,John Doe,16.0,Male,10th,64.0,missing,67,2022-06-12,good student
27,127,Simran Singh,16.0,FEMALE,12,NaN,76,80,2022-06-12,poor
28,128,Sara O'Neil,17.0,female,11,NaN,64,89,2022-10-06,average
29,129,Patel R.,17.0,male,11,NaN,64,83,2022-11-06,Average
30,129,Patel R.,17.0,male,11,NaN,64,83,2022-11-06,Average