<a href="https://colab.research.google.com/github/2410030121/DataScience/blob/main/Missing_Values(Weather_Data).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv("weather_data.csv",parse_dates=['day'])
type(df.day[0])
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [ ]:
new_df=df.fillna(0)
new_df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          0.0        9.0   Sunny
2 2017-01-05         28.0        0.0    Snow
3 2017-01-06          0.0        7.0       0
4 2017-01-07         32.0        0.0    Rain
5 2017-01-08          0.0        0.0   Sunny
6 2017-01-09          0.0        0.0       0
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [ ]:
new_df=df.fillna({
    'temperature':0,
    'windspeed':0,
    'event':'no event'
})
new_df

         day  temperature  windspeed     event
0 2017-01-01         32.0        6.0      Rain
1 2017-01-04          0.0        9.0     Sunny
2 2017-01-05         28.0        0.0      Snow
3 2017-01-06          0.0        7.0  no event
4 2017-01-07         32.0        0.0      Rain
5 2017-01-08          0.0        0.0     Sunny
6 2017-01-09          0.0        0.0  no event
7 2017-01-10         34.0        8.0    Cloudy
8 2017-01-11         40.0       12.0     Sunny

In [ ]:
new_df=df.ffill()
new_df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         32.0        9.0   Sunny
2 2017-01-05         28.0        9.0    Snow
3 2017-01-06         28.0        7.0    Snow
4 2017-01-07         32.0        7.0    Rain
5 2017-01-08         32.0        7.0   Sunny
6 2017-01-09         32.0        7.0   Sunny
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [ ]:
new_df=df.bfill()
new_df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         28.0        9.0   Sunny
2 2017-01-05         28.0        7.0    Snow
3 2017-01-06         32.0        7.0    Rain
4 2017-01-07         32.0        8.0    Rain
5 2017-01-08         34.0        8.0   Sunny
6 2017-01-09         34.0        8.0  Cloudy
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [ ]:
display(df)

         day  temperature  windspeed   event
0 2017-01-01    32.000000       6.00    Rain
1 2017-01-04    30.000000       9.00   Sunny
2 2017-01-05    28.000000       8.00    Snow
4 2017-01-07    32.000000       7.25    Rain
5 2017-01-08    32.666667       7.50   Sunny
7 2017-01-10    34.000000       8.00  Cloudy
8 2017-01-11    40.000000      12.00   Sunny

In [ ]:
df = df.interpolate()
new_df

/tmp/ipykernel_2471/2524736170.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df = df.interpolate()

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         28.0        9.0   Sunny
2 2017-01-05         28.0        7.0    Snow
3 2017-01-06         32.0        7.0    Rain
4 2017-01-07         32.0        8.0    Rain
5 2017-01-08         34.0        8.0   Sunny
6 2017-01-09         34.0        8.0  Cloudy
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [ ]:
df = df.dropna()
new_df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         28.0        9.0   Sunny
2 2017-01-05         28.0        7.0    Snow
3 2017-01-06         32.0        7.0    Rain
4 2017-01-07         32.0        8.0    Rain
5 2017-01-08         34.0        8.0   Sunny
6 2017-01-09         34.0        8.0  Cloudy
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny